# Generated by Django 3.0.5 on 2020-04-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20200411_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='setting.MEDIA_COMPANY_IMAGE_DIR'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='logo',
            field=models.ImageField(upload_to='setting.MEDIA_COMPANY_IMAGE_DIR'),
        ),
    ]
