# Generated by Django 3.0.5 on 2020-04-15 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0004_auto_20200414_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='grade',
            field=models.CharField(choices=[('st', 'Стажер'), ('j', 'Джуниор'), ('m', 'Миддл'), ('sr', 'Синьор'), ('l', 'Лид')], default='j', max_length=2),
        ),
        migrations.AlterField(
            model_name='resume',
            name='specialty',
            field=models.ForeignKey(default='backend', on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='job.Specialty'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('n', 'Не ищу работу'), ('r', 'Рассматриваю предложения'), ('a', 'Ищу работу')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL),
        ),
    ]
